export const stateSalesTax = {
    "Alabama": 4.00,
    "Alaska": 0.00,
    "Arizona": 8.60,
    "Arkansas": 9.30,
    "California": 7.25,
    "Colorado": 2.90,
    "Connecticut": 6.35,
    "Delaware": 0.00,
    "Florida": 6.00,
    "Georgia": 4.00,
    "Hawaii": 4.00,
    "Idaho": 6.00,
    "Illinois": 6.25,
    "Indiana": 7.00,
    "Iowa": 6.00,
    "Kansas": 8.60,
    "Kentucky": 6.00,
    "Louisiana": 4.45,
    "Maine": 5.50,
    "Maryland": 6.00,
    "Massachusetts": 6.25,
    "Michigan": 6.00,
    "Minnesota": 6.88,
    "Mississippi": 7.00,
    "Missouri": 4.23,
    "Montana": 0.00,
    "Nebraska": 5.50,
    "Nevada": 8.25,
    "New Hampshire": 0.00,
    "New Jersey": 6.625,
    "New Mexico": 5.13,
    "New York": 4.00,
    "North Carolina": 4.75,
    "North Dakota": 5.00,
    "Ohio": 5.75,
    "Oklahoma": 4.50,
    "Oregon": 0.00,
    "Pennsylvania": 6.00,
    "Rhode Island": 7.00,
    "South Carolina": 6.00,
    "South Dakota": 4.50,
    "Tennessee": 7.00,
    "Texas": 6.25,
    "Utah": 4.70,
    "Vermont": 6.00,
    "Virginia": 5.30,
    "Washington": 6.50,
    "West Virginia": 6.00,
    "Wisconsin": 5.00,
    "Wyoming": 4.00
};

export const usStates = ['Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming']
